# zero shot evaluation
train_file: ['data/finetune/nlvr_en/nlvr_train.json']
val_file: ['data/finetune/nlvr_en/nlvr_dev.json']
image_root: 'images/nlvr2/'

test_file: {
  'en': 'data/finetune/nlvr_en/nlvr_test.json',  # i use NLVR2 test set here. i didn't find IGLUE en test set
  'zh': 'data/marvl/marvl-zh.json',
  'id': 'data/marvl/marvl-id.json',
  'sw': 'data/marvl/marvl-sw.json',
  'ta': 'data/marvl/marvl-ta.json',
  'tr': 'data/marvl/marvl-tr.json' }


## Vision Encoder
vision_config: 'configs/config_swinB_384.json'

use_clip_vit: False
#image_res: 384
#patch_size: 16

use_swin: True
image_res: 384
patch_size: 32


## Text Encoder (& Cross Encoder)
text_encoder: 'data/xlm-roberta-large'
text_num_hidden_layers: 12



## Training
batch_size: 10


## Other Settings
optimizer: {opt: adamW, lr: 3e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 3e-5, epochs: 10, num_warmup_steps: 0.1}
start_eval: 6  # epoch index

