# English-only Fine-tune

train_file:  ['data/finetune/mscoco/en.train.json']

val_file: {'en': 'data/finetune/mscoco/en.val.json',
           'zh': 'data/finetune/mscoco/zh.val.json',
           'ja': 'data/finetune/mscoco/ja.val.json'}

test_file: {'en': 'data/finetune/mscoco/en.test.json',
           'zh': 'data/finetune/mscoco/zh.test.json',
           'ja': 'data/finetune/mscoco/ja.test.json'}


image_root: 'images/'

## Vision Encoder
vision_config: 'configs/config_swinB_384.json'

use_clip_vit: False
#image_res: 384
#patch_size: 16

use_swin: True
image_res: 384
patch_size: 32


## Text Encoder (& Cross Encoder)
text_encoder: 'data/xlm-roberta-large'
text_num_hidden_layers: 12



## Training
use_one_cl_proj_only: False

batch_size_train: 20
batch_size_test: 12
batch_size_test_text: 64
max_tokens: 40
embed_dim: 256
temp: 0.07
k_test: 256


## Other Settings
optimizer: {opt: adamW, lr: 3e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 3e-5, epochs: 10, num_warmup_steps: 0.1}

