# Zeroshot Finetune
train_file:  ['iglue/datasets/flickr30k/annotations/train_ann.jsonl']

val_file: 'iglue/datasets/flickr30k/annotations/valid_ann.jsonl'

test_file: {'de': 'iglue/datasets/xFlickrCO/annotations/de/test.jsonl',
           'en': 'iglue/datasets/xFlickrCO/annotations/en/test.jsonl',
           'es': 'iglue/datasets/xFlickrCO/annotations/es/test.jsonl',
           'id': 'iglue/datasets/xFlickrCO/annotations/id/test.jsonl',
           'ja': 'iglue/datasets/xFlickrCO/annotations/ja/test.jsonl',
           'ru': 'iglue/datasets/xFlickrCO/annotations/ru/test.jsonl',
           'tr': 'iglue/datasets/xFlickrCO/annotations/tr/test.jsonl',
           'zh': 'iglue/datasets/xFlickrCO/annotations/zh/test.jsonl'}

gmt_test_file: {'de': 'iglue/datasets/xFlickrCO/annotations_machine-translate/de/test_gmt.jsonl',
           'es': 'iglue/datasets/xFlickrCO/annotations_machine-translate/es/test_gmt.jsonl',
           'id': 'iglue/datasets/xFlickrCO/annotations_machine-translate/id/test_gmt.jsonl',
           'ja': 'iglue/datasets/xFlickrCO/annotations_machine-translate/ja/test_gmt.jsonl',
           'ru': 'iglue/datasets/xFlickrCO/annotations_machine-translate/ru/test_gmt.jsonl',
           'tr': 'iglue/datasets/xFlickrCO/annotations_machine-translate/tr/test_gmt.jsonl',
           'zh': 'iglue/datasets/xFlickrCO/annotations_machine-translate/zh/test_gmt.jsonl'}

image_root: {'flickr30k': 'images/flickr30k-images',
            'coco': 'images/val2014'}
            

## Vision Encoder
vision_config: 'configs/config_swinB_384.json'

use_clip_vit: False
#image_res: 384
#patch_size: 16

use_swin: True
image_res: 384
patch_size: 32


## Text Encoder (& Cross Encoder)
text_encoder: 'data/xlm-roberta-large'
text_num_hidden_layers: 12

## Training
batch_size_train: 8
batch_size_test: 12
batch_size_test_text: 64
max_tokens: 80
embed_dim: 256
temp: 0.07
k_test: 128
use_one_cl_proj_only: False

## Other Settings
optimizer: {opt: adamW, lr: 3e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 3e-5, epochs: 10, num_warmup_steps: 0.1}
start_eval: 7
eval_interval: 1