# few shot evaluation
# iglue fewshot: 1, 5, 10, 20, 25, 48
train_file: ['iglue/datasets/XVNLI/annotations/{}/train_{}.jsonl']
val_file: ['iglue/datasets/XVNLI/annotations/{}/test.jsonl']  # 'data/finetune/nlvr_en/nlvr_test.json'

test_file: {}

image_root: 'images/flickr30k-images'

## Vision Encoder
vision_config: 'configs/config_swinB_384.json'

use_clip_vit: False
#image_res: 384
#patch_size: 16

use_swin: True
image_res: 384
patch_size: 32

## Text Encoder (& Cross Encoder)
text_encoder: 'data/xlm-roberta-large'
text_num_hidden_layers: 12
max_tokens: 80

num_labels: 3

## Training
batch_size: 12
use_one_cl_proj_only: False

## Other Settings
# iglue paper: 1e-5, 5e-5, 1e-4
optimizer: {opt: adamW, lr: 1e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 1e-5, epochs: 60, num_warmup_steps: 0.1}
start_eval: 9
eval_interval: 10
