# zero shot evaluation
train_file: ['iglue/datasets/XVNLI/annotations/en/train.jsonl']
val_file: ['iglue/datasets/XVNLI/annotations/en/dev.jsonl']  # 'data/finetune/nlvr_en/nlvr_test.json'

test_file: {'ar': 'iglue/datasets/XVNLI/annotations/ar/test.jsonl',
           'en': 'iglue/datasets/XVNLI/annotations/en/test.jsonl',
           'es': 'iglue/datasets/XVNLI/annotations/es/test.jsonl',
           'fr': 'iglue/datasets/XVNLI/annotations/fr/test.jsonl',
           'ru': 'iglue/datasets/XVNLI/annotations/ru/test.jsonl',}

gmt_test_file: {'ar': 'iglue/datasets/XVNLI/annotations_machine-translate/ar/test.jsonl',
           'es': 'iglue/datasets/XVNLI/annotations_machine-translate/es/test.jsonl',
           'fr': 'iglue/datasets/XVNLI/annotations_machine-translate/fr/test.jsonl',
           'ru': 'iglue/datasets/XVNLI/annotations_machine-translate/ru/test.jsonl'}

image_root: 'images/flickr30k-images'

## Vision Encoder
vision_config: 'configs/config_swinB_384.json'

use_clip_vit: False
#image_res: 384
#patch_size: 16

use_swin: True
image_res: 384
patch_size: 32

## Text Encoder (& Cross Encoder)
text_encoder: 'data/xlm-roberta-large'
text_num_hidden_layers: 12
max_tokens: 80

num_labels: 3

## Training
batch_size: 12
use_one_cl_proj_only: False

## Other Settings
optimizer: {opt: adamW, lr: 3e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 3e-5, epochs: 10, num_warmup_steps: 0.1}
start_eval: 0
eval_interval: 1